package net.fellter.vanillalayerplus.registry;

import java.util.LinkedHashMap;
import java.util.Map;

import net.fellter.vanillalayerplus.block.ModBlocks;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.client.data.TextureMap;
import net.minecraft.client.render.item.tint.ConstantTintSource;
import net.minecraft.client.render.item.tint.GrassTintSource;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.util.Identifier;

import static net.fellter.vanillalayerplus.util.ModTextureMap.*;

public final class Args {
	public static Map<Block, DatagenArgs> DATAGEN_ARGS = new LinkedHashMap<>();
	public static Map<Block, RegistryArgs> REGISTRY_ARGS = new LinkedHashMap<>();

	private static void putInDatagenArgs(Block block, DatagenArgs datagenArgs) {
		DatagenArgs oldArgs = DATAGEN_ARGS.put(block, datagenArgs);
		if (oldArgs == null) {
			DATAGEN_ARGS.put(block, datagenArgs);
		} else {
			throw new IllegalStateException("Block " + block.getName() + " has already been put in DatagenArgs source map.");
		}
	}

	private static void putInRegistryArgs(Block block, RegistryArgs registryArgs) {
		RegistryArgs oldArgs = REGISTRY_ARGS.put(block, registryArgs);
		if (oldArgs == null) {
			REGISTRY_ARGS.put(block, registryArgs);
		} else {
			throw new IllegalStateException("Block " + block.getName() + " has already been put in RegistryArgs source map.");
		}
	}

	public static void registerDatagenArgs() {
		putInDatagenArgs(ModBlocks.OAK_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.OAK_PLANKS).textureMap(TextureMap.all(Blocks.OAK_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_OAK_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_OAK_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_OAK_LOG)));
		putInDatagenArgs(ModBlocks.OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.OAK_LOG).textureMap(blockAndTopForEnds(Blocks.OAK_LOG)));
		putInDatagenArgs(ModBlocks.OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.OAK_WOOD).textureMap(TextureMap.all(Blocks.OAK_LOG)));
		putInDatagenArgs(ModBlocks.SPRUCE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.SPRUCE_PLANKS).textureMap(TextureMap.all(Blocks.SPRUCE_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_SPRUCE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_SPRUCE_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_SPRUCE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_SPRUCE_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.SPRUCE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.SPRUCE_LOG).textureMap(blockAndTopForEnds(Blocks.SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.SPRUCE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.SPRUCE_WOOD).textureMap(TextureMap.all(Blocks.SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.BIRCH_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BIRCH_PLANKS).textureMap(TextureMap.all(Blocks.BIRCH_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_BIRCH_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_BIRCH_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_BIRCH_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_BIRCH_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.BIRCH_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BIRCH_LOG).textureMap(blockAndTopForEnds(Blocks.BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.BIRCH_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BIRCH_WOOD).textureMap(TextureMap.all(Blocks.BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.JUNGLE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.JUNGLE_PLANKS).textureMap(TextureMap.all(Blocks.JUNGLE_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_JUNGLE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_JUNGLE_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_JUNGLE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_JUNGLE_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.JUNGLE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.JUNGLE_LOG).textureMap(blockAndTopForEnds(Blocks.JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.JUNGLE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.JUNGLE_WOOD).textureMap(TextureMap.all(Blocks.JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.ACACIA_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.ACACIA_PLANKS).textureMap(TextureMap.all(Blocks.ACACIA_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_ACACIA_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_ACACIA_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_ACACIA_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_ACACIA_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.ACACIA_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.ACACIA_LOG).textureMap(blockAndTopForEnds(Blocks.ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.ACACIA_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.ACACIA_WOOD).textureMap(TextureMap.all(Blocks.ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.DARK_OAK_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.DARK_OAK_PLANKS).textureMap(TextureMap.all(Blocks.DARK_OAK_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_DARK_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_DARK_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_DARK_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_DARK_OAK_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.DARK_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.DARK_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.DARK_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.DARK_OAK_WOOD).textureMap(TextureMap.all(Blocks.DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.MANGROVE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.MANGROVE_PLANKS).textureMap(TextureMap.all(Blocks.MANGROVE_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_MANGROVE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_MANGROVE_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_MANGROVE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_MANGROVE_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.MANGROVE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.MANGROVE_LOG).textureMap(blockAndTopForEnds(Blocks.MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.MANGROVE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.MANGROVE_WOOD).textureMap(TextureMap.all(Blocks.MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.CHERRY_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.CHERRY_PLANKS).textureMap(TextureMap.all(Blocks.CHERRY_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_CHERRY_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_CHERRY_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_CHERRY_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_CHERRY_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.CHERRY_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.CHERRY_LOG).textureMap(blockAndTopForEnds(Blocks.CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.CHERRY_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.CHERRY_WOOD).textureMap(TextureMap.all(Blocks.CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.PALE_OAK_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.PALE_OAK_PLANKS).textureMap(TextureMap.all(Blocks.PALE_OAK_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_PALE_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_PALE_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_PALE_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_PALE_OAK_WOOD).textureMap(TextureMap.all(Blocks.STRIPPED_PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.PALE_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.PALE_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.PALE_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.PALE_OAK_WOOD).textureMap(TextureMap.all(Blocks.PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.BAMBOO_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BAMBOO_PLANKS).textureMap(TextureMap.all(Blocks.BAMBOO_PLANKS)));
		putInDatagenArgs(ModBlocks.BAMBOO_MOSAIC_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BAMBOO_MOSAIC).textureMap(TextureMap.all(Blocks.BAMBOO_MOSAIC)));
		putInDatagenArgs(ModBlocks.STRIPPED_BAMBOO_BLOCK_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_BAMBOO_BLOCK).textureMap(blockAndTopForEnds(Blocks.STRIPPED_BAMBOO_BLOCK)));
		putInDatagenArgs(ModBlocks.BAMBOO_BLOCK_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BAMBOO_BLOCK).textureMap(blockAndTopForEnds(Blocks.BAMBOO_BLOCK)));
		putInDatagenArgs(ModBlocks.CRIMSON_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.CRIMSON_PLANKS).textureMap(TextureMap.all(Blocks.CRIMSON_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_CRIMSON_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_CRIMSON_STEM).textureMap(blockAndTopForEnds(Blocks.STRIPPED_CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.STRIPPED_CRIMSON_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_CRIMSON_HYPHAE).textureMap(TextureMap.all(Blocks.STRIPPED_CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.CRIMSON_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.CRIMSON_STEM).textureMap(blockAndTopForEnds(Blocks.CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.CRIMSON_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.CRIMSON_HYPHAE).textureMap(TextureMap.all(Blocks.CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.WARPED_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.WARPED_PLANKS).textureMap(TextureMap.all(Blocks.WARPED_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_WARPED_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_WARPED_STEM).textureMap(blockAndTopForEnds(Blocks.STRIPPED_WARPED_STEM)));
		putInDatagenArgs(ModBlocks.STRIPPED_WARPED_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.STRIPPED_WARPED_HYPHAE).textureMap(TextureMap.all(Blocks.STRIPPED_WARPED_STEM)));
		putInDatagenArgs(ModBlocks.WARPED_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.WARPED_STEM).textureMap(blockAndTopForEnds(Blocks.WARPED_STEM)));
		putInDatagenArgs(ModBlocks.WARPED_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.WARPED_HYPHAE).textureMap(TextureMap.all(Blocks.WARPED_STEM)));
		putInDatagenArgs(ModBlocks.STONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.STONE).textureMap(TextureMap.all(Blocks.STONE)).stonecutting());
		putInDatagenArgs(ModBlocks.COBBLESTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COBBLESTONE).textureMap(TextureMap.all(Blocks.COBBLESTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.MOSSY_COBBLESTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MOSSY_COBBLESTONE).textureMap(TextureMap.all(Blocks.MOSSY_COBBLESTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.SMOOTH_STONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SMOOTH_STONE).textureMap(TextureMap.all(Blocks.SMOOTH_STONE)).stonecutting());
		putInDatagenArgs(ModBlocks.STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.STONE_BRICKS).textureMap(TextureMap.all(Blocks.STONE_BRICKS)).stonecutting(Blocks.STONE));
		putInDatagenArgs(ModBlocks.CRACKED_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRACKED_STONE_BRICKS).textureMap(TextureMap.all(Blocks.CRACKED_STONE_BRICKS)));
		putInDatagenArgs(ModBlocks.CHISELED_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRACKED_STONE_BRICKS).textureMap(TextureMap.all(Blocks.CHISELED_STONE_BRICKS)).stonecutting(Blocks.STONE, Blocks.STONE_BRICKS));
		putInDatagenArgs(ModBlocks.MOSSY_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MOSSY_STONE_BRICKS).textureMap(TextureMap.all(Blocks.MOSSY_STONE_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.GRANITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GRANITE).textureMap(TextureMap.all(Blocks.GRANITE)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_GRANITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_GRANITE).textureMap(TextureMap.all(Blocks.POLISHED_GRANITE)).stonecutting(Blocks.GRANITE));
		putInDatagenArgs(ModBlocks.DIORITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DIORITE).textureMap(TextureMap.all(Blocks.DIORITE)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_DIORITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_DIORITE).textureMap(TextureMap.all(Blocks.POLISHED_DIORITE)).stonecutting(Blocks.DIORITE));
		putInDatagenArgs(ModBlocks.ANDESITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.ANDESITE).textureMap(TextureMap.all(Blocks.ANDESITE)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_ANDESITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_ANDESITE).textureMap(TextureMap.all(Blocks.POLISHED_ANDESITE)).stonecutting(Blocks.ANDESITE));
		putInDatagenArgs(ModBlocks.DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE).textureMap(blockAndTopForEnds(Blocks.DEEPSLATE)));
		putInDatagenArgs(ModBlocks.COBBLED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COBBLED_DEEPSLATE).textureMap(TextureMap.all(Blocks.COBBLED_DEEPSLATE)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_DEEPSLATE).textureMap(TextureMap.all(Blocks.CHISELED_DEEPSLATE)).stonecutting(Blocks.COBBLED_DEEPSLATE));
		putInDatagenArgs(ModBlocks.POLISHED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_DEEPSLATE).textureMap(TextureMap.all(Blocks.POLISHED_DEEPSLATE)).stonecutting());
		putInDatagenArgs(ModBlocks.DEEPSLATE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_BRICKS).textureMap(TextureMap.all(Blocks.DEEPSLATE_BRICKS)).stonecutting(Blocks.COBBLED_DEEPSLATE, Blocks.POLISHED_DEEPSLATE));
		putInDatagenArgs(ModBlocks.CRACKED_DEEPSLATE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRACKED_DEEPSLATE_BRICKS).textureMap(TextureMap.all(Blocks.CRACKED_DEEPSLATE_BRICKS)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_TILES_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_TILES).textureMap(TextureMap.all(Blocks.DEEPSLATE_TILES)).stonecutting(Blocks.POLISHED_DEEPSLATE, Blocks.DEEPSLATE_BRICKS));
		putInDatagenArgs(ModBlocks.CRACKED_DEEPSLATE_TILES_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRACKED_DEEPSLATE_TILES).textureMap(TextureMap.all(Blocks.CRACKED_DEEPSLATE_TILES)));
		putInDatagenArgs(ModBlocks.TUFF_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.TUFF).textureMap(TextureMap.all(Blocks.TUFF)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_TUFF_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_TUFF).textureMap(blockAndTopForEnds(Blocks.CHISELED_TUFF)).stonecutting(Blocks.TUFF));
		putInDatagenArgs(ModBlocks.POLISHED_TUFF_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_TUFF).textureMap(TextureMap.all(Blocks.POLISHED_TUFF)).stonecutting(Blocks.TUFF));
		putInDatagenArgs(ModBlocks.TUFF_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.TUFF_BRICKS).textureMap(TextureMap.all(Blocks.TUFF_BRICKS)).stonecutting(Blocks.POLISHED_TUFF, Blocks.TUFF));
		putInDatagenArgs(ModBlocks.CHISELED_TUFF_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_TUFF_BRICKS).textureMap(blockAndTopForEnds(Blocks.CHISELED_TUFF_BRICKS)).stonecutting(Blocks.POLISHED_TUFF, Blocks.TUFF_BRICKS));
		putInDatagenArgs(ModBlocks.BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BRICKS).textureMap(TextureMap.all(Blocks.BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.PACKED_MUD_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PACKED_MUD).textureMap(TextureMap.all(Blocks.PACKED_MUD)));
		putInDatagenArgs(ModBlocks.MUD_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MUD_BRICKS).textureMap(TextureMap.all(Blocks.MUD_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.RESIN_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RESIN_BRICKS).textureMap(TextureMap.all(Blocks.RESIN_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_RESIN_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_RESIN_BRICKS).textureMap(TextureMap.all(Blocks.CHISELED_RESIN_BRICKS)).stonecutting(Blocks.RESIN_BRICKS));
		putInDatagenArgs(ModBlocks.SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SANDSTONE).textureMap(blockTB(Blocks.SANDSTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_SANDSTONE).textureMap(custom(Blocks.CHISELED_SANDSTONE, Blocks.SANDSTONE, Blocks.SANDSTONE, "", "_top", "_top")).stonecutting(Blocks.SANDSTONE));
		putInDatagenArgs(ModBlocks.SMOOTH_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SMOOTH_SANDSTONE).textureMap(allWithSuffix(Blocks.SANDSTONE, "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.CUT_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CUT_SANDSTONE).textureMap(custom(Blocks.CUT_SANDSTONE, Blocks.SANDSTONE, Blocks.SANDSTONE, "", "_top", "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RED_SANDSTONE).textureMap(blockTB(Blocks.RED_SANDSTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_RED_SANDSTONE).textureMap(custom(Blocks.CHISELED_RED_SANDSTONE, Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE, "", "_top", "_top")).stonecutting(Blocks.RED_SANDSTONE));
		putInDatagenArgs(ModBlocks.SMOOTH_RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SMOOTH_RED_SANDSTONE).textureMap(allWithSuffix(Blocks.RED_SANDSTONE, "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.CUT_RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CUT_RED_SANDSTONE).textureMap(custom(Blocks.CUT_RED_SANDSTONE, Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE, "", "_top", "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.SEA_LANTERN_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SEA_LANTERN).textureMap(TextureMap.all(Blocks.SEA_LANTERN)));
		putInDatagenArgs(ModBlocks.PRISMARINE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PRISMARINE).textureMap(TextureMap.all(Blocks.PRISMARINE)).stonecutting());
		putInDatagenArgs(ModBlocks.PRISMARINE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PRISMARINE_BRICKS).textureMap(TextureMap.all(Blocks.PRISMARINE_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.DARK_PRISMARINE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DARK_PRISMARINE).textureMap(TextureMap.all(Blocks.DARK_PRISMARINE)).stonecutting());
		putInDatagenArgs(ModBlocks.NETHERRACK_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.NETHERRACK).textureMap(TextureMap.all(Blocks.NETHERRACK)));
		putInDatagenArgs(ModBlocks.NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.NETHER_BRICKS).textureMap(TextureMap.all(Blocks.NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.CRACKED_NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRACKED_NETHER_BRICKS).textureMap(TextureMap.all(Blocks.CRACKED_NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.CHISELED_NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_NETHER_BRICKS).textureMap(TextureMap.all(Blocks.CHISELED_NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.RED_NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RED_NETHER_BRICKS).textureMap(TextureMap.all(Blocks.RED_NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.BASALT_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BASALT).textureMap(sideAndTopForEnds(Blocks.BASALT)));
		putInDatagenArgs(ModBlocks.SMOOTH_BASALT_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SMOOTH_BASALT).textureMap(TextureMap.all(Blocks.SMOOTH_BASALT)));
		putInDatagenArgs(ModBlocks.POLISHED_BASALT_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_BASALT).textureMap(sideAndTopForEnds(Blocks.POLISHED_BASALT)));
		putInDatagenArgs(ModBlocks.BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLACKSTONE).textureMap(blockAndTopForEnds(Blocks.BLACKSTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.GILDED_BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GILDED_BLACKSTONE).textureMap(TextureMap.all(Blocks.GILDED_BLACKSTONE)));
		putInDatagenArgs(ModBlocks.CHISELED_POLISHED_BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_POLISHED_BLACKSTONE).textureMap(TextureMap.all(Blocks.CHISELED_POLISHED_BLACKSTONE)).stonecutting(Blocks.POLISHED_BLACKSTONE, Blocks.BLACKSTONE));
		putInDatagenArgs(ModBlocks.POLISHED_BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_BLACKSTONE).textureMap(TextureMap.all(Blocks.POLISHED_BLACKSTONE)).stonecutting(Blocks.BLACKSTONE));
		putInDatagenArgs(ModBlocks.POLISHED_BLACKSTONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.POLISHED_BLACKSTONE_BRICKS).textureMap(TextureMap.all(Blocks.POLISHED_BLACKSTONE_BRICKS)).stonecutting(Blocks.POLISHED_BLACKSTONE));
		putInDatagenArgs(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS).textureMap(TextureMap.all(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)));
		putInDatagenArgs(ModBlocks.END_STONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.END_STONE).textureMap(TextureMap.all(Blocks.END_STONE)).stonecutting());
		putInDatagenArgs(ModBlocks.END_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.END_STONE_BRICKS).textureMap(TextureMap.all(Blocks.END_STONE_BRICKS)).stonecutting(Blocks.END_STONE));
		putInDatagenArgs(ModBlocks.PURPUR_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PURPUR_BLOCK).textureMap(TextureMap.all(Blocks.PURPUR_BLOCK)));
		putInDatagenArgs(ModBlocks.PURPUR_PILLAR_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PURPUR_PILLAR).textureMap(blockAndTopForEnds(Blocks.PURPUR_PILLAR)));
		putInDatagenArgs(ModBlocks.COAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COAL_BLOCK).textureMap(TextureMap.all(Blocks.COAL_BLOCK)));
		putInDatagenArgs(ModBlocks.IRON_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.IRON_BLOCK).textureMap(TextureMap.all(Blocks.IRON_BLOCK)));
		putInDatagenArgs(ModBlocks.GOLD_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GOLD_BLOCK).textureMap(TextureMap.all(Blocks.GOLD_BLOCK)));
		putInDatagenArgs(ModBlocks.REDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.REDSTONE_BLOCK).textureMap(TextureMap.all(Blocks.REDSTONE_BLOCK)));
		putInDatagenArgs(ModBlocks.EMERALD_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.EMERALD_BLOCK).textureMap(TextureMap.all(Blocks.EMERALD_BLOCK)));
		putInDatagenArgs(ModBlocks.LAPIS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LAPIS_BLOCK).textureMap(TextureMap.all(Blocks.LAPIS_BLOCK)));
		putInDatagenArgs(ModBlocks.DIAMOND_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DIAMOND_BLOCK).textureMap(TextureMap.all(Blocks.DIAMOND_BLOCK)));
		putInDatagenArgs(ModBlocks.NETHERITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.NETHERITE_BLOCK).textureMap(TextureMap.all(Blocks.NETHERITE_BLOCK)));
		putInDatagenArgs(ModBlocks.QUARTZ_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.QUARTZ_BLOCK).textureMap(blockSTB(Blocks.QUARTZ_BLOCK)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_QUARTZ_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_QUARTZ_BLOCK).textureMap(blockAndTopForEnds(Blocks.CHISELED_QUARTZ_BLOCK)).stonecutting(Blocks.QUARTZ_BLOCK));
		putInDatagenArgs(ModBlocks.QUARTZ_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.QUARTZ_BRICKS).textureMap(TextureMap.all(Blocks.QUARTZ_BRICKS)).stonecutting(Blocks.QUARTZ_BLOCK));
		putInDatagenArgs(ModBlocks.QUARTZ_PILLAR_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.QUARTZ_PILLAR).textureMap(blockAndTopForEnds(Blocks.QUARTZ_PILLAR)).stonecutting(Blocks.QUARTZ_BLOCK));
		putInDatagenArgs(ModBlocks.SMOOTH_QUARTZ_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.SMOOTH_QUARTZ).textureMap(allWithSuffix(Blocks.QUARTZ_BLOCK, "_bottom")).stonecutting());
		putInDatagenArgs(ModBlocks.AMETHYST_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.AMETHYST_BLOCK).textureMap(TextureMap.all(Blocks.AMETHYST_BLOCK)));
		putInDatagenArgs(ModBlocks.WAXED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_COPPER_BLOCK, Blocks.COPPER_BLOCK).textureMap(TextureMap.all(Blocks.COPPER_BLOCK)).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_CHISELED_COPPER, Blocks.CHISELED_COPPER).textureMap(TextureMap.all(Blocks.CHISELED_COPPER)).stonecutting(Blocks.WAXED_COPPER_BLOCK));
		putInDatagenArgs(ModBlocks.WAXED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_COPPER_GRATE, Blocks.COPPER_GRATE).textureMap(TextureMap.all(Blocks.COPPER_GRATE)).stonecutting(Blocks.WAXED_COPPER_BLOCK));
		putInDatagenArgs(ModBlocks.WAXED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_CUT_COPPER, Blocks.CUT_COPPER).textureMap(TextureMap.all(Blocks.CUT_COPPER)).stonecutting(Blocks.WAXED_COPPER_BLOCK));
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_EXPOSED_COPPER, Blocks.EXPOSED_COPPER).textureMap(TextureMap.all(Blocks.EXPOSED_COPPER)).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_EXPOSED_CHISELED_COPPER, Blocks.EXPOSED_CHISELED_COPPER).textureMap(TextureMap.all(Blocks.EXPOSED_CHISELED_COPPER)).stonecutting(Blocks.WAXED_EXPOSED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_EXPOSED_COPPER_GRATE, Blocks.EXPOSED_COPPER_GRATE).textureMap(TextureMap.all(Blocks.EXPOSED_COPPER_GRATE)).stonecutting(Blocks.WAXED_EXPOSED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_EXPOSED_CUT_COPPER, Blocks.EXPOSED_CUT_COPPER).textureMap(TextureMap.all(Blocks.EXPOSED_CUT_COPPER)).stonecutting(Blocks.WAXED_EXPOSED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_WEATHERED_COPPER, Blocks.WEATHERED_COPPER).textureMap(TextureMap.all(Blocks.WEATHERED_COPPER)).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_WEATHERED_CHISELED_COPPER, Blocks.WEATHERED_CHISELED_COPPER).textureMap(TextureMap.all(Blocks.WEATHERED_CHISELED_COPPER)).stonecutting(Blocks.WAXED_WEATHERED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_WEATHERED_COPPER_GRATE, Blocks.WEATHERED_COPPER_GRATE).textureMap(TextureMap.all(Blocks.WEATHERED_COPPER_GRATE)).stonecutting(Blocks.WAXED_WEATHERED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_WEATHERED_CUT_COPPER, Blocks.WEATHERED_CUT_COPPER).textureMap(TextureMap.all(Blocks.WEATHERED_CUT_COPPER)).stonecutting(Blocks.WAXED_WEATHERED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_OXIDIZED_COPPER, Blocks.OXIDIZED_COPPER).textureMap(TextureMap.all(Blocks.OXIDIZED_COPPER)).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_OXIDIZED_CHISELED_COPPER, Blocks.OXIDIZED_CHISELED_COPPER).textureMap(TextureMap.all(Blocks.OXIDIZED_CHISELED_COPPER)).stonecutting(Blocks.WAXED_OXIDIZED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_OXIDIZED_COPPER_GRATE, Blocks.OXIDIZED_COPPER_GRATE).textureMap(TextureMap.all(Blocks.OXIDIZED_COPPER_GRATE)).stonecutting(Blocks.WAXED_OXIDIZED_COPPER));
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WAXED_OXIDIZED_CUT_COPPER, Blocks.OXIDIZED_CUT_COPPER).textureMap(TextureMap.all(Blocks.OXIDIZED_CUT_COPPER)).stonecutting(Blocks.WAXED_OXIDIZED_COPPER));
		putInDatagenArgs(ModBlocks.EXPOSED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.EXPOSED_COPPER).textureMap(TextureMap.all(Blocks.EXPOSED_COPPER)).stonecutting());
		putInDatagenArgs(ModBlocks.EXPOSED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.EXPOSED_CHISELED_COPPER).textureMap(TextureMap.all(Blocks.EXPOSED_CHISELED_COPPER)).stonecutting(Blocks.EXPOSED_COPPER));
		putInDatagenArgs(ModBlocks.EXPOSED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.EXPOSED_COPPER_GRATE).textureMap(TextureMap.all(Blocks.EXPOSED_COPPER_GRATE)).stonecutting(Blocks.EXPOSED_COPPER));
		putInDatagenArgs(ModBlocks.EXPOSED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.EXPOSED_CUT_COPPER).textureMap(TextureMap.all(Blocks.EXPOSED_CUT_COPPER)).stonecutting(Blocks.EXPOSED_COPPER));
		putInDatagenArgs(ModBlocks.WEATHERED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WEATHERED_COPPER).textureMap(TextureMap.all(Blocks.WEATHERED_COPPER)).stonecutting());
		putInDatagenArgs(ModBlocks.WEATHERED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WEATHERED_CHISELED_COPPER).textureMap(TextureMap.all(Blocks.WEATHERED_CHISELED_COPPER)).stonecutting(Blocks.WEATHERED_COPPER));
		putInDatagenArgs(ModBlocks.WEATHERED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WEATHERED_COPPER_GRATE).textureMap(TextureMap.all(Blocks.WEATHERED_COPPER_GRATE)).stonecutting(Blocks.WEATHERED_COPPER));
		putInDatagenArgs(ModBlocks.WEATHERED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WEATHERED_CUT_COPPER).textureMap(TextureMap.all(Blocks.WEATHERED_CUT_COPPER)).stonecutting(Blocks.WEATHERED_COPPER));
		putInDatagenArgs(ModBlocks.OXIDIZED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.OXIDIZED_COPPER).textureMap(TextureMap.all(Blocks.OXIDIZED_COPPER)).stonecutting());
		putInDatagenArgs(ModBlocks.OXIDIZED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.OXIDIZED_CHISELED_COPPER).textureMap(TextureMap.all(Blocks.OXIDIZED_CHISELED_COPPER)).stonecutting(Blocks.OXIDIZED_COPPER));
		putInDatagenArgs(ModBlocks.OXIDIZED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.OXIDIZED_COPPER_GRATE).textureMap(TextureMap.all(Blocks.OXIDIZED_COPPER_GRATE)).stonecutting(Blocks.OXIDIZED_COPPER));
		putInDatagenArgs(ModBlocks.OXIDIZED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.OXIDIZED_CUT_COPPER).textureMap(TextureMap.all(Blocks.OXIDIZED_CUT_COPPER)).stonecutting(Blocks.OXIDIZED_COPPER));
		putInDatagenArgs(ModBlocks.COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COPPER_BLOCK).textureMap(TextureMap.all(Blocks.COPPER_BLOCK)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CHISELED_COPPER).textureMap(TextureMap.all(Blocks.CHISELED_COPPER)).stonecutting(Blocks.COPPER_BLOCK));
		putInDatagenArgs(ModBlocks.COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COPPER_GRATE).textureMap(TextureMap.all(Blocks.COPPER_GRATE)).stonecutting(Blocks.COPPER_BLOCK));
		putInDatagenArgs(ModBlocks.CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CUT_COPPER).textureMap(TextureMap.all(Blocks.CUT_COPPER)).stonecutting(Blocks.COPPER_BLOCK));
		putInDatagenArgs(ModBlocks.WHITE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WHITE_WOOL).textureMap(TextureMap.all(Blocks.WHITE_WOOL)));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.LIGHT_GRAY_WOOL).textureMap(TextureMap.all(Blocks.LIGHT_GRAY_WOOL)));
		putInDatagenArgs(ModBlocks.GRAY_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.GRAY_WOOL).textureMap(TextureMap.all(Blocks.GRAY_WOOL)));
		putInDatagenArgs(ModBlocks.BLACK_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.BLACK_WOOL).textureMap(TextureMap.all(Blocks.BLACK_WOOL)));
		putInDatagenArgs(ModBlocks.BROWN_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.BROWN_WOOL).textureMap(TextureMap.all(Blocks.BROWN_WOOL)));
		putInDatagenArgs(ModBlocks.RED_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.RED_WOOL).textureMap(TextureMap.all(Blocks.RED_WOOL)));
		putInDatagenArgs(ModBlocks.ORANGE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.ORANGE_WOOL).textureMap(TextureMap.all(Blocks.ORANGE_WOOL)));
		putInDatagenArgs(ModBlocks.YELLOW_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.YELLOW_WOOL).textureMap(TextureMap.all(Blocks.YELLOW_WOOL)));
		putInDatagenArgs(ModBlocks.LIME_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.LIME_WOOL).textureMap(TextureMap.all(Blocks.LIME_WOOL)));
		putInDatagenArgs(ModBlocks.GREEN_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.GREEN_WOOL).textureMap(TextureMap.all(Blocks.GREEN_WOOL)));
		putInDatagenArgs(ModBlocks.CYAN_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.CYAN_WOOL).textureMap(TextureMap.all(Blocks.CYAN_WOOL)));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.LIGHT_BLUE_WOOL).textureMap(TextureMap.all(Blocks.LIGHT_BLUE_WOOL)));
		putInDatagenArgs(ModBlocks.BLUE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.BLUE_WOOL).textureMap(TextureMap.all(Blocks.BLUE_WOOL)));
		putInDatagenArgs(ModBlocks.PURPLE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.PURPLE_WOOL).textureMap(TextureMap.all(Blocks.PURPLE_WOOL)));
		putInDatagenArgs(ModBlocks.MAGENTA_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.MAGENTA_WOOL).textureMap(TextureMap.all(Blocks.MAGENTA_WOOL)));
		putInDatagenArgs(ModBlocks.PINK_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.PINK_WOOL).textureMap(TextureMap.all(Blocks.PINK_WOOL)));
		putInDatagenArgs(ModBlocks.WHITE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.WHITE_TERRACOTTA).textureMap(TextureMap.all(Blocks.WHITE_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.LIGHT_GRAY_TERRACOTTA).textureMap(TextureMap.all(Blocks.LIGHT_GRAY_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.GRAY_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.GRAY_TERRACOTTA).textureMap(TextureMap.all(Blocks.GRAY_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.BLACK_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.BLACK_TERRACOTTA).textureMap(TextureMap.all(Blocks.BLACK_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.BROWN_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.BROWN_TERRACOTTA).textureMap(TextureMap.all(Blocks.BROWN_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.RED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.RED_TERRACOTTA).textureMap(TextureMap.all(Blocks.RED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.ORANGE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.ORANGE_TERRACOTTA).textureMap(TextureMap.all(Blocks.ORANGE_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.YELLOW_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.YELLOW_TERRACOTTA).textureMap(TextureMap.all(Blocks.YELLOW_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.LIME_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.LIME_TERRACOTTA).textureMap(TextureMap.all(Blocks.LIME_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.GREEN_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.GREEN_TERRACOTTA).textureMap(TextureMap.all(Blocks.GREEN_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.CYAN_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.CYAN_TERRACOTTA).textureMap(TextureMap.all(Blocks.CYAN_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.LIGHT_BLUE_TERRACOTTA).textureMap(TextureMap.all(Blocks.LIGHT_BLUE_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.BLUE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.BLUE_TERRACOTTA).textureMap(TextureMap.all(Blocks.BLUE_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.PURPLE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.PURPLE_TERRACOTTA).textureMap(TextureMap.all(Blocks.PURPLE_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.MAGENTA_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.MAGENTA_TERRACOTTA).textureMap(TextureMap.all(Blocks.MAGENTA_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.PINK_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE, BlockTags.TERRACOTTA).parentBlock(Blocks.PINK_TERRACOTTA).textureMap(TextureMap.all(Blocks.PINK_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.WHITE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WHITE_CONCRETE).textureMap(TextureMap.all(Blocks.WHITE_CONCRETE)));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIGHT_GRAY_CONCRETE).textureMap(TextureMap.all(Blocks.LIGHT_GRAY_CONCRETE)));
		putInDatagenArgs(ModBlocks.GRAY_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GRAY_CONCRETE).textureMap(TextureMap.all(Blocks.GRAY_CONCRETE)));
		putInDatagenArgs(ModBlocks.BLACK_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLACK_CONCRETE).textureMap(TextureMap.all(Blocks.BLACK_CONCRETE)));
		putInDatagenArgs(ModBlocks.BROWN_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BROWN_CONCRETE).textureMap(TextureMap.all(Blocks.BROWN_CONCRETE)));
		putInDatagenArgs(ModBlocks.RED_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RED_CONCRETE).textureMap(TextureMap.all(Blocks.RED_CONCRETE)));
		putInDatagenArgs(ModBlocks.ORANGE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.ORANGE_CONCRETE).textureMap(TextureMap.all(Blocks.ORANGE_CONCRETE)));
		putInDatagenArgs(ModBlocks.YELLOW_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.YELLOW_CONCRETE).textureMap(TextureMap.all(Blocks.YELLOW_CONCRETE)));
		putInDatagenArgs(ModBlocks.LIME_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIME_CONCRETE).textureMap(TextureMap.all(Blocks.LIME_CONCRETE)));
		putInDatagenArgs(ModBlocks.GREEN_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GREEN_CONCRETE).textureMap(TextureMap.all(Blocks.GREEN_CONCRETE)));
		putInDatagenArgs(ModBlocks.CYAN_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CYAN_CONCRETE).textureMap(TextureMap.all(Blocks.CYAN_CONCRETE)));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIGHT_BLUE_CONCRETE).textureMap(TextureMap.all(Blocks.LIGHT_BLUE_CONCRETE)));
		putInDatagenArgs(ModBlocks.BLUE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLUE_CONCRETE).textureMap(TextureMap.all(Blocks.BLUE_CONCRETE)));
		putInDatagenArgs(ModBlocks.PURPLE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PURPLE_CONCRETE).textureMap(TextureMap.all(Blocks.PURPLE_CONCRETE)));
		putInDatagenArgs(ModBlocks.MAGENTA_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MAGENTA_CONCRETE).textureMap(TextureMap.all(Blocks.MAGENTA_CONCRETE)));
		putInDatagenArgs(ModBlocks.PINK_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PINK_CONCRETE).textureMap(TextureMap.all(Blocks.PINK_CONCRETE)));
		putInDatagenArgs(ModBlocks.WHITE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.WHITE_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.WHITE_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.LIGHT_GRAY_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.LIGHT_GRAY_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.GRAY_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.GRAY_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.GRAY_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.BLACK_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.BLACK_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.BLACK_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.BROWN_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.BROWN_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.BROWN_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.RED_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.RED_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.RED_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.ORANGE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.ORANGE_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.ORANGE_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.YELLOW_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.YELLOW_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.YELLOW_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.LIME_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.LIME_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.LIME_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.GREEN_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.GREEN_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.GREEN_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.CYAN_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.CYAN_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.CYAN_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.LIGHT_BLUE_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.LIGHT_BLUE_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.BLUE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.BLUE_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.BLUE_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.PURPLE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.PURPLE_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.PURPLE_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.MAGENTA_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.MAGENTA_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.MAGENTA_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.PINK_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.PINK_CONCRETE_POWDER).textureMap(TextureMap.all(Blocks.PINK_CONCRETE_POWDER)));
		putInDatagenArgs(ModBlocks.WHITE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WHITE_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.WHITE_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.GRAY_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GRAY_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.GRAY_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.BLACK_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLACK_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.BLACK_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.BROWN_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BROWN_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.BROWN_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.RED_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RED_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.RED_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.ORANGE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.ORANGE_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.ORANGE_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.YELLOW_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.YELLOW_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.YELLOW_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.LIME_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIME_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.LIME_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.GREEN_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GREEN_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.GREEN_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.CYAN_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CYAN_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.CYAN_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.BLUE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLUE_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.BLUE_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.PURPLE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PURPLE_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.PURPLE_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MAGENTA_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.MAGENTA_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.PINK_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PINK_GLAZED_TERRACOTTA).textureMap(TextureMap.all(Blocks.PINK_GLAZED_TERRACOTTA)));
		putInDatagenArgs(ModBlocks.GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GLASS).textureMap(TextureMap.all(Blocks.GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.WHITE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WHITE_STAINED_GLASS).textureMap(TextureMap.all(Blocks.WHITE_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIGHT_GRAY_STAINED_GLASS).textureMap(TextureMap.all(Blocks.LIGHT_GRAY_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.GRAY_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GRAY_STAINED_GLASS).textureMap(TextureMap.all(Blocks.GRAY_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.BLACK_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLACK_STAINED_GLASS).textureMap(TextureMap.all(Blocks.BLACK_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.BROWN_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BROWN_STAINED_GLASS).textureMap(TextureMap.all(Blocks.BROWN_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.RED_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RED_STAINED_GLASS).textureMap(TextureMap.all(Blocks.RED_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.ORANGE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.ORANGE_STAINED_GLASS).textureMap(TextureMap.all(Blocks.ORANGE_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.YELLOW_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.YELLOW_STAINED_GLASS).textureMap(TextureMap.all(Blocks.YELLOW_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.LIME_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIME_STAINED_GLASS).textureMap(TextureMap.all(Blocks.LIME_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.GREEN_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GREEN_STAINED_GLASS).textureMap(TextureMap.all(Blocks.GREEN_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.CYAN_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CYAN_STAINED_GLASS).textureMap(TextureMap.all(Blocks.CYAN_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LIGHT_BLUE_STAINED_GLASS).textureMap(TextureMap.all(Blocks.LIGHT_BLUE_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.BLUE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLUE_STAINED_GLASS).textureMap(TextureMap.all(Blocks.BLUE_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.PURPLE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PURPLE_STAINED_GLASS).textureMap(TextureMap.all(Blocks.PURPLE_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.MAGENTA_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MAGENTA_STAINED_GLASS).textureMap(TextureMap.all(Blocks.MAGENTA_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.PINK_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PINK_STAINED_GLASS).textureMap(TextureMap.all(Blocks.PINK_STAINED_GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.DIRT_PATH_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.DIRT_PATH).textureMap(custom(Blocks.DIRT_PATH, Blocks.DIRT_PATH, Blocks.DIRT, "_side", "_top", "")).y15());
		putInDatagenArgs(ModBlocks.FARMLAND_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.FARMLAND).textureMap(custom(Blocks.DIRT, Blocks.FARMLAND, Blocks.DIRT, "", "", "")).y15());
		putInDatagenArgs(ModBlocks.DIRT_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.DIRT).textureMap(TextureMap.all(Blocks.DIRT)));
		putInDatagenArgs(ModBlocks.GRASS_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.GRASS_BLOCK).tintSource(new GrassTintSource()));
		putInDatagenArgs(ModBlocks.PODZOL_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.PODZOL).textureMap(custom(Blocks.PODZOL, Blocks.PODZOL, Blocks.DIRT, "_side", "_top", "")));
		putInDatagenArgs(ModBlocks.MYCELIUM_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.MYCELIUM).textureMap(custom(Blocks.MYCELIUM, Blocks.MYCELIUM, Blocks.DIRT, "_side", "_top", "")));
		putInDatagenArgs(ModBlocks.COARSE_DIRT_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.COARSE_DIRT).textureMap(TextureMap.all(Blocks.COARSE_DIRT)));
		putInDatagenArgs(ModBlocks.ROOTED_DIRT_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.ROOTED_DIRT).textureMap(TextureMap.all(Blocks.ROOTED_DIRT)));
		putInDatagenArgs(ModBlocks.MUD_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.MUD).textureMap(TextureMap.all(Blocks.MUD)));
		putInDatagenArgs(ModBlocks.CLAY_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.CLAY).textureMap(TextureMap.all(Blocks.CLAY)));
		putInDatagenArgs(ModBlocks.GRAVEL_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.GRAVEL).textureMap(TextureMap.all(Blocks.GRAVEL)));
		putInDatagenArgs(ModBlocks.SAND_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.SAND).textureMap(TextureMap.all(Blocks.SAND)));
		putInDatagenArgs(ModBlocks.ICE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.ICE).textureMap(TextureMap.all(Blocks.ICE)));
		putInDatagenArgs(ModBlocks.PACKED_ICE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.PACKED_ICE).textureMap(TextureMap.all(Blocks.PACKED_ICE)));
		putInDatagenArgs(ModBlocks.BLUE_ICE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BLUE_ICE).textureMap(TextureMap.all(Blocks.BLUE_ICE)));
		putInDatagenArgs(ModBlocks.SNOW_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.SNOW_BLOCK).textureMap(TextureMap.all(Blocks.SNOW)));
		putInDatagenArgs(ModBlocks.MOSS_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.MOSS_BLOCK).textureMap(TextureMap.all(Blocks.MOSS_BLOCK)));
		putInDatagenArgs(ModBlocks.PALE_MOSS_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.PALE_MOSS_BLOCK).textureMap(TextureMap.all(Blocks.PALE_MOSS_BLOCK)));
		putInDatagenArgs(ModBlocks.CALCITE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CALCITE).textureMap(TextureMap.all(Blocks.CALCITE)));
		putInDatagenArgs(ModBlocks.DRIPSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DRIPSTONE_BLOCK).textureMap(TextureMap.all(Blocks.DRIPSTONE_BLOCK)));
		putInDatagenArgs(ModBlocks.MAGMA_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.MAGMA_BLOCK).textureMap(TextureMap.all(Identifier.ofVanilla("block/magma"))));
		putInDatagenArgs(ModBlocks.OBSIDIAN_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.OBSIDIAN).textureMap(TextureMap.all(Blocks.OBSIDIAN)));
		putInDatagenArgs(ModBlocks.CRYING_OBSIDIAN_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRYING_OBSIDIAN).textureMap(TextureMap.all(Blocks.CRYING_OBSIDIAN)));
		putInDatagenArgs(ModBlocks.CRIMSON_NYLIUM_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.CRIMSON_NYLIUM).textureMap(custom(Blocks.CRIMSON_NYLIUM, Blocks.CRIMSON_NYLIUM, Blocks.NETHERRACK, "_side", "", "")));
		putInDatagenArgs(ModBlocks.WARPED_NYLIUM_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.WARPED_NYLIUM).textureMap(custom(Blocks.WARPED_NYLIUM, Blocks.WARPED_NYLIUM, Blocks.NETHERRACK, "_side", "", "")));
		putInDatagenArgs(ModBlocks.SOUL_SAND_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.SOUL_SAND).textureMap(TextureMap.all(Blocks.SOUL_SAND)));
		putInDatagenArgs(ModBlocks.SOUL_SOIL_LAYER, new DatagenArgs().blockTags(BlockTags.SHOVEL_MINEABLE).parentBlock(Blocks.SOUL_SOIL).textureMap(TextureMap.all(Blocks.SOUL_SOIL)));
		putInDatagenArgs(ModBlocks.BONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BONE_BLOCK).textureMap(sideAndTopForEnds(Blocks.BONE_BLOCK)));
		putInDatagenArgs(ModBlocks.COAL_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COAL_ORE).textureMap(TextureMap.all(Blocks.COAL_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_COAL_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_COAL_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_COAL_ORE)));
		putInDatagenArgs(ModBlocks.IRON_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.IRON_ORE).textureMap(TextureMap.all(Blocks.IRON_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_IRON_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_IRON_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_IRON_ORE)));
		putInDatagenArgs(ModBlocks.COPPER_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.COPPER_ORE).textureMap(TextureMap.all(Blocks.COPPER_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_COPPER_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_COPPER_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_COPPER_ORE)));
		putInDatagenArgs(ModBlocks.GOLD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GOLD_ORE).textureMap(TextureMap.all(Blocks.GOLD_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_GOLD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_GOLD_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_GOLD_ORE)));
		putInDatagenArgs(ModBlocks.REDSTONE_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.REDSTONE_ORE).textureMap(TextureMap.all(Blocks.REDSTONE_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_REDSTONE_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_REDSTONE_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_REDSTONE_ORE)));
		putInDatagenArgs(ModBlocks.EMERALD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.EMERALD_ORE).textureMap(TextureMap.all(Blocks.EMERALD_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_EMERALD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_EMERALD_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_EMERALD_ORE)));
		putInDatagenArgs(ModBlocks.LAPIS_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.LAPIS_ORE).textureMap(TextureMap.all(Blocks.LAPIS_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_LAPIS_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_LAPIS_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_LAPIS_ORE)));
		putInDatagenArgs(ModBlocks.DIAMOND_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DIAMOND_ORE).textureMap(TextureMap.all(Blocks.DIAMOND_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_DIAMOND_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEEPSLATE_DIAMOND_ORE).textureMap(TextureMap.all(Blocks.DEEPSLATE_DIAMOND_ORE)));
		putInDatagenArgs(ModBlocks.NETHER_GOLD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.NETHER_GOLD_ORE).textureMap(TextureMap.all(Blocks.NETHER_GOLD_ORE)));
		putInDatagenArgs(ModBlocks.NETHER_QUARTZ_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.NETHER_QUARTZ_ORE).textureMap(TextureMap.all(Blocks.NETHER_QUARTZ_ORE)));
		putInDatagenArgs(ModBlocks.ANCIENT_DEBRIS_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.ANCIENT_DEBRIS).textureMap(sideAndTopForEnds(Blocks.ANCIENT_DEBRIS)));
		putInDatagenArgs(ModBlocks.RAW_IRON_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RAW_IRON_BLOCK).textureMap(TextureMap.all(Blocks.RAW_IRON_BLOCK)));
		putInDatagenArgs(ModBlocks.RAW_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RAW_COPPER_BLOCK).textureMap(TextureMap.all(Blocks.RAW_COPPER_BLOCK)));
		putInDatagenArgs(ModBlocks.RAW_GOLD_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.RAW_GOLD_BLOCK).textureMap(TextureMap.all(Blocks.RAW_GOLD_BLOCK)));
		putInDatagenArgs(ModBlocks.GLOWSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.GLOWSTONE).textureMap(TextureMap.all(Blocks.GLOWSTONE)));
		putInDatagenArgs(ModBlocks.OAK_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.OAK_LEAVES).textureMap(TextureMap.all(Blocks.OAK_LEAVES)).tintSource(new ConstantTintSource(-12012264)));
		putInDatagenArgs(ModBlocks.SPRUCE_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.SPRUCE_LEAVES).textureMap(TextureMap.all(Blocks.SPRUCE_LEAVES)).tintSource(new ConstantTintSource(-10380959)));
		putInDatagenArgs(ModBlocks.BIRCH_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.BIRCH_LEAVES).textureMap(TextureMap.all(Blocks.BIRCH_LEAVES)).tintSource(new ConstantTintSource(-8345771)));
		putInDatagenArgs(ModBlocks.JUNGLE_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.JUNGLE_LEAVES).textureMap(TextureMap.all(Blocks.JUNGLE_LEAVES)).tintSource(new ConstantTintSource(-12012264)));
		putInDatagenArgs(ModBlocks.ACACIA_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.ACACIA_LEAVES).textureMap(TextureMap.all(Blocks.ACACIA_LEAVES)).tintSource(new ConstantTintSource(-12012264)));
		putInDatagenArgs(ModBlocks.DARK_OAK_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.DARK_OAK_LEAVES).textureMap(TextureMap.all(Blocks.DARK_OAK_LEAVES)).tintSource(new ConstantTintSource(-12012264)));
		putInDatagenArgs(ModBlocks.MANGROVE_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.MANGROVE_LEAVES).textureMap(TextureMap.all(Blocks.MANGROVE_LEAVES)).tintSource(new ConstantTintSource(-7158200)));
		putInDatagenArgs(ModBlocks.CHERRY_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.CHERRY_LEAVES).textureMap(TextureMap.all(Blocks.CHERRY_LEAVES)));
		putInDatagenArgs(ModBlocks.PALE_OAK_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.PALE_OAK_LEAVES).textureMap(TextureMap.all(Blocks.PALE_OAK_LEAVES)));
		putInDatagenArgs(ModBlocks.AZALEA_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.AZALEA_LEAVES).textureMap(TextureMap.all(Blocks.AZALEA_LEAVES)));
		putInDatagenArgs(ModBlocks.FLOWERING_AZALEA_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.FLOWERING_AZALEA_LEAVES).textureMap(TextureMap.all(Blocks.FLOWERING_AZALEA_LEAVES)));
		putInDatagenArgs(ModBlocks.BROWN_MUSHROOM_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.BROWN_MUSHROOM_BLOCK));
		putInDatagenArgs(ModBlocks.RED_MUSHROOM_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.RED_MUSHROOM_BLOCK));
		putInDatagenArgs(ModBlocks.NETHER_WART_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.NETHER_WART_BLOCK).textureMap(TextureMap.all(Blocks.NETHER_WART_BLOCK)));
		putInDatagenArgs(ModBlocks.WARPED_WART_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.WARPED_WART_BLOCK).textureMap(TextureMap.all(Blocks.WARPED_WART_BLOCK)));
		putInDatagenArgs(ModBlocks.SHROOMLIGHT_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.SHROOMLIGHT).textureMap(TextureMap.all(Blocks.SHROOMLIGHT)));
		putInDatagenArgs(ModBlocks.DRIED_KELP_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.DRIED_KELP_BLOCK).textureMap(blockSTB(Identifier.ofVanilla("block/dried_kelp"))));
		putInDatagenArgs(ModBlocks.TUBE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.TUBE_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.TUBE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.BRAIN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BRAIN_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.BRAIN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.BUBBLE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.BUBBLE_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.BUBBLE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.FIRE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.FIRE_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.FIRE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.HORN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.HORN_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.HORN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_TUBE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEAD_TUBE_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.DEAD_TUBE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_BRAIN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEAD_BRAIN_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.DEAD_BRAIN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_BUBBLE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEAD_BUBBLE_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.DEAD_BUBBLE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_FIRE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEAD_FIRE_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.DEAD_FIRE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_HORN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.PICKAXE_MINEABLE).parentBlock(Blocks.DEAD_HORN_CORAL_BLOCK).textureMap(TextureMap.all(Blocks.DEAD_HORN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.SPONGE_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.SPONGE).textureMap(TextureMap.all(Blocks.SPONGE)));
		putInDatagenArgs(ModBlocks.WET_SPONGE_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.WET_SPONGE).textureMap(TextureMap.all(Blocks.WET_SPONGE)));
		putInDatagenArgs(ModBlocks.MELON_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.MELON).textureMap(sideAndTopForEnds(Blocks.MELON)));
		putInDatagenArgs(ModBlocks.PUMPKIN_LAYER, new DatagenArgs().blockTags(BlockTags.AXE_MINEABLE).parentBlock(Blocks.PUMPKIN).textureMap(sideAndTopForEnds(Blocks.PUMPKIN)));
		putInDatagenArgs(ModBlocks.HAY_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.HAY_BLOCK).textureMap(sideAndTopForEnds(Blocks.HAY_BLOCK)));
		putInDatagenArgs(ModBlocks.HONEYCOMB_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.HONEYCOMB_BLOCK).textureMap(TextureMap.all(Blocks.HONEYCOMB_BLOCK)));
		putInDatagenArgs(ModBlocks.SLIME_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.SLIME_BLOCK).textureMap(TextureMap.all(Blocks.SLIME_BLOCK)));
		putInDatagenArgs(ModBlocks.HONEY_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.HONEY_BLOCK).textureMap(blockSTB(Blocks.HONEY_BLOCK)));
		putInDatagenArgs(ModBlocks.RESIN_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.RESIN_BLOCK).textureMap(TextureMap.all(Blocks.RESIN_BLOCK)));
		putInDatagenArgs(ModBlocks.OCHRE_FROGLIGHT_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.OCHRE_FROGLIGHT).textureMap(sideAndTopForEnds(Blocks.OCHRE_FROGLIGHT)));
		putInDatagenArgs(ModBlocks.VERDANT_FROGLIGHT_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.VERDANT_FROGLIGHT).textureMap(sideAndTopForEnds(Blocks.VERDANT_FROGLIGHT)));
		putInDatagenArgs(ModBlocks.PEARLESCENT_FROGLIGHT_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.PEARLESCENT_FROGLIGHT).textureMap(sideAndTopForEnds(Blocks.PEARLESCENT_FROGLIGHT)));
		putInDatagenArgs(ModBlocks.SCULK_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.SCULK).textureMap(TextureMap.all(Blocks.SCULK)));
		putInDatagenArgs(ModBlocks.BEDROCK_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.BEDROCK).textureMap(TextureMap.all(Blocks.BEDROCK)));
		putInDatagenArgs(ModBlocks.TARGET_LAYER, new DatagenArgs().blockTags(BlockTags.HOE_MINEABLE).parentBlock(Blocks.TARGET).textureMap(sideAndTopForEnds(Blocks.TARGET)));
		
		
	}
	
	public static void registerRegistryArgs() {
		putInRegistryArgs(ModBlocks.OAK_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.OAK_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_OAK_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.OAK_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_OAK_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_OAK_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_OAK_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.SPRUCE_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.SPRUCE_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_SPRUCE_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.SPRUCE_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_SPRUCE_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_SPRUCE_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_SPRUCE_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.BIRCH_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.BIRCH_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_BIRCH_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.BIRCH_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_BIRCH_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_BIRCH_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_BIRCH_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.JUNGLE_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.JUNGLE_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_JUNGLE_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.JUNGLE_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_JUNGLE_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_JUNGLE_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_JUNGLE_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.ACACIA_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.ACACIA_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_ACACIA_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.ACACIA_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_ACACIA_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_ACACIA_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_ACACIA_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.DARK_OAK_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.DARK_OAK_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_DARK_OAK_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.DARK_OAK_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_DARK_OAK_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_DARK_OAK_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_DARK_OAK_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.MANGROVE_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.MANGROVE_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_MANGROVE_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.MANGROVE_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_MANGROVE_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_MANGROVE_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_MANGROVE_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.CHERRY_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.CHERRY_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CHERRY_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.CHERRY_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CHERRY_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_CHERRY_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_CHERRY_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.PALE_OAK_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.PALE_OAK_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_PALE_OAK_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.PALE_OAK_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_PALE_OAK_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_PALE_OAK_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_PALE_OAK_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.BAMBOO_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.BAMBOO_MOSAIC_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.BAMBOO_BLOCK_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_BAMBOO_BLOCK_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_BAMBOO_BLOCK_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.CRIMSON_STEM_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CRIMSON_STEM_LAYER));
		putInRegistryArgs(ModBlocks.CRIMSON_HYPHAE_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CRIMSON_HYPHAE_LAYER));
		putInRegistryArgs(ModBlocks.WARPED_STEM_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_WARPED_STEM_LAYER));
		putInRegistryArgs(ModBlocks.WARPED_HYPHAE_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_WARPED_HYPHAE_LAYER));
		putInRegistryArgs(ModBlocks.WAXED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WAXED_EXPOSED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WAXED_WEATHERED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WAXED_OXIDIZED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.EXPOSED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WEATHERED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.OXIDIZED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.COPPER_LAYER, new RegistryArgs().oxidizable(ModBlocks.EXPOSED_COPPER_LAYER, ModBlocks.WEATHERED_COPPER_LAYER, ModBlocks.OXIDIZED_COPPER_LAYER, ModBlocks.WAXED_COPPER_LAYER, ModBlocks.WAXED_EXPOSED_COPPER_LAYER, ModBlocks.WAXED_WEATHERED_COPPER_LAYER, ModBlocks.WAXED_OXIDIZED_COPPER_LAYER));
		putInRegistryArgs(ModBlocks.CHISELED_COPPER_LAYER, new RegistryArgs().oxidizable(ModBlocks.EXPOSED_CHISELED_COPPER_LAYER, ModBlocks.WEATHERED_CHISELED_COPPER_LAYER, ModBlocks.OXIDIZED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_EXPOSED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_WEATHERED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_OXIDIZED_CHISELED_COPPER_LAYER));
		putInRegistryArgs(ModBlocks.COPPER_GRATE_LAYER, new RegistryArgs().transparent().oxidizable(ModBlocks.EXPOSED_COPPER_GRATE_LAYER, ModBlocks.WEATHERED_COPPER_GRATE_LAYER, ModBlocks.OXIDIZED_COPPER_GRATE_LAYER, ModBlocks.WAXED_COPPER_GRATE_LAYER, ModBlocks.WEATHERED_COPPER_GRATE_LAYER, ModBlocks.WAXED_WEATHERED_COPPER_GRATE_LAYER, ModBlocks.WAXED_OXIDIZED_COPPER_GRATE_LAYER));
		putInRegistryArgs(ModBlocks.CUT_COPPER_LAYER, new RegistryArgs().oxidizable(ModBlocks.EXPOSED_CUT_COPPER_LAYER, ModBlocks.WEATHERED_CUT_COPPER_LAYER, ModBlocks.OXIDIZED_CUT_COPPER_LAYER, ModBlocks.WAXED_CUT_COPPER_LAYER, ModBlocks.WAXED_EXPOSED_CUT_COPPER_LAYER, ModBlocks.WAXED_WEATHERED_CUT_COPPER_LAYER, ModBlocks.WAXED_OXIDIZED_CUT_COPPER_LAYER));
		putInRegistryArgs(ModBlocks.GLASS_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WHITE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.LIGHT_GRAY_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.GRAY_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BLACK_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BROWN_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.RED_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.ORANGE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.YELLOW_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.LIME_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.GREEN_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.CYAN_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.LIGHT_BLUE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BLUE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PURPLE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.MAGENTA_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PINK_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.DIRT_LAYER, new RegistryArgs().tillable(ModBlocks.FARMLAND_LAYER).flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.GRASS_LAYER, new RegistryArgs().transparent().grassTinted().flattenable(ModBlocks.DIRT_PATH_LAYER).tillable(ModBlocks.FARMLAND_LAYER));
		putInRegistryArgs(ModBlocks.PODZOL_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.MYCELIUM_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.COARSE_DIRT_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.ROOTED_DIRT_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.ICE_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PACKED_ICE_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BLUE_ICE_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PALE_MOSS_LAYER, new RegistryArgs().flammable(5, 100));
		putInRegistryArgs(ModBlocks.OAK_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.SPRUCE_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.BIRCH_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.JUNGLE_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.ACACIA_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.DARK_OAK_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.MANGROVE_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.CHERRY_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.PALE_OAK_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.AZALEA_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.FLOWERING_AZALEA_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.SLIME_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.HONEY_LAYER, new RegistryArgs().translucent());
		
	}
}
